server:
  port: 8080

spring:
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8000
          predicates:
            - Path=/expenses/**
        - id: notification-service
          uri: http://notification-service:8001
          predicates:
            - Path=/notification/**