# Generated by Django 4.2.1 on 2023-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_profile_picture_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
