version: '3.8'

services:
  django:
    build: ../../..
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moneysage
      - POSTGRES_USER=moneysage
      - POSTGRES_PASSWORD=moneysage
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
