version: '3.8'

services:
  user-service:
    build: ../user-service
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ../user-service/.env
    depends_on:
      - db
    networks:
      - moneysage-network

  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moneysage
      - POSTGRES_USER=moneysage
      - POSTGRES_PASSWORD=moneysage
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - moneysage-network

networks:
  moneysage-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  postgres_data:
