version: '3.8'

services:

  notification-serive:
    build: ../microservices/notification-service
    ports:
      - "8001:8001"
    expose:
      - "8001"
    env_file:
      - ../microservices/notification-service/.env
    depends_on:
      - db

  user-service:
    build: ../microservices/user-service
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ../microservices/user-service/.env
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moneysage
      - POSTGRES_USER=moneysage
      - POSTGRES_PASSWORD=moneysage
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
