# Generated by Django 4.2.1 on 2023-06-18 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999)),
                ('currency', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=120)),
                ('payment_type', models.CharField(max_length=120)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('amountConverted', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999)),
                ('currency', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=120)),
                ('payment_type', models.CharField(max_length=120)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('amountConverted', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.ManyToManyField(to='transactions.expense')),
                ('incomes', models.ManyToManyField(to='transactions.income')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_wallet', to='transactions.walletmodel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_wallet', to='transactions.walletmodel'),
        ),
    ]
