# Generated by Django 4.2.1 on 2023-07-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_expense_wallet_remove_income_wallet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amountConverted',
            new_name='converted_amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='amountConverted',
            new_name='converted_amount',
        ),
    ]
